#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("PlusSample.Resource", IsApplication=true)]

namespace PlusSample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int buttonSize = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int circleCrop = 2130771970;
			
			// aapt resource value: 0x7f010004
			public const int colorScheme = 2130771972;
			
			// aapt resource value: 0x7f010001
			public const int imageAspectRatio = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int imageAspectRatioAdjust = 2130771968;
			
			// aapt resource value: 0x7f010005
			public const int scopeUris = 2130771973;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060008
			public const int common_google_signin_btn_text_dark = 2131099656;
			
			// aapt resource value: 0x7f060000
			public const int common_google_signin_btn_text_dark_default = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int common_google_signin_btn_text_dark_disabled = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int common_google_signin_btn_text_dark_focused = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int common_google_signin_btn_text_dark_pressed = 2131099651;
			
			// aapt resource value: 0x7f060009
			public const int common_google_signin_btn_text_light = 2131099657;
			
			// aapt resource value: 0x7f060004
			public const int common_google_signin_btn_text_light_default = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int common_google_signin_btn_text_light_disabled = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int common_google_signin_btn_text_light_focused = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int common_google_signin_btn_text_light_pressed = 2131099655;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int common_full_open_on_phone = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int common_google_signin_btn_icon_dark = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int common_google_signin_btn_icon_dark_disabled = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_google_signin_btn_icon_dark_focused = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_google_signin_btn_icon_dark_normal = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_google_signin_btn_icon_dark_pressed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_google_signin_btn_icon_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_google_signin_btn_icon_light_disabled = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_google_signin_btn_icon_light_focused = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_google_signin_btn_icon_light_normal = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_google_signin_btn_icon_light_pressed = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_google_signin_btn_text_dark = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_google_signin_btn_text_dark_disabled = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_google_signin_btn_text_dark_focused = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_google_signin_btn_text_dark_normal = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_google_signin_btn_text_dark_pressed = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_google_signin_btn_text_light = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_google_signin_btn_text_light_disabled = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_google_signin_btn_text_light_focused = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_google_signin_btn_text_light_normal = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_google_signin_btn_text_light_pressed = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int ic_launcher = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int ic_plusone_medium_off_client = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int ic_plusone_small_off_client = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int ic_plusone_standard_off_client = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int ic_plusone_tall_off_client = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int Icon = 2130837530;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080000
			public const int adjust_height = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int adjust_width = 2131230721;
			
			// aapt resource value: 0x7f080006
			public const int auto = 2131230726;
			
			// aapt resource value: 0x7f08001b
			public const int change_locale = 2131230747;
			
			// aapt resource value: 0x7f080007
			public const int dark = 2131230727;
			
			// aapt resource value: 0x7f080003
			public const int icon_only = 2131230723;
			
			// aapt resource value: 0x7f080008
			public const int light = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int moment_list = 2131230729;
			
			// aapt resource value: 0x7f08000b
			public const int moment_title = 2131230731;
			
			// aapt resource value: 0x7f08000a
			public const int moment_type = 2131230730;
			
			// aapt resource value: 0x7f080002
			public const int none = 2131230722;
			
			// aapt resource value: 0x7f08000c
			public const int person_list = 2131230732;
			
			// aapt resource value: 0x7f08000e
			public const int plus_one_medium_button = 2131230734;
			
			// aapt resource value: 0x7f08000d
			public const int plus_one_small_button = 2131230733;
			
			// aapt resource value: 0x7f080011
			public const int plus_one_standard_ann_button = 2131230737;
			
			// aapt resource value: 0x7f080010
			public const int plus_one_standard_button = 2131230736;
			
			// aapt resource value: 0x7f08000f
			public const int plus_one_tall_button = 2131230735;
			
			// aapt resource value: 0x7f080019
			public const int revoke_access_button = 2131230745;
			
			// aapt resource value: 0x7f080014
			public const int scope_selection_toggle = 2131230740;
			
			// aapt resource value: 0x7f080013
			public const int send_interactive_button = 2131230739;
			
			// aapt resource value: 0x7f080017
			public const int server_auth_code_disabled = 2131230743;
			
			// aapt resource value: 0x7f080016
			public const int server_auth_code_reset_button = 2131230742;
			
			// aapt resource value: 0x7f080012
			public const int share_prefill_edit = 2131230738;
			
			// aapt resource value: 0x7f080015
			public const int sign_in_button = 2131230741;
			
			// aapt resource value: 0x7f08001a
			public const int sign_in_status = 2131230746;
			
			// aapt resource value: 0x7f080018
			public const int sign_out_button = 2131230744;
			
			// aapt resource value: 0x7f080004
			public const int standard = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int wide = 2131230725;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f040000
			public const int google_play_services_version = 2130968576;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int list_moments_activity = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int main_list_item = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int moment_row = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int multi_moment_activity = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int person_list_activity = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int plus_one_activity = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int share_activity = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int sign_in_activity = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int main_activity_menu = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050011
			public const int app_name = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int change_locale = 2131034130;
			
			// aapt resource value: 0x7f050001
			public const int common_google_play_services_enable_button = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int common_google_play_services_enable_text = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int common_google_play_services_enable_title = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int common_google_play_services_install_button = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int common_google_play_services_install_text = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int common_google_play_services_install_title = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int common_google_play_services_notification_ticker = 2131034119;
			
			// aapt resource value: 0x7f050000
			public const int common_google_play_services_unknown_issue = 2131034112;
			
			// aapt resource value: 0x7f050008
			public const int common_google_play_services_unsupported_text = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int common_google_play_services_update_button = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int common_google_play_services_update_text = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int common_google_play_services_update_title = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int common_google_play_services_updating_text = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int common_google_play_services_wear_update_text = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int common_open_on_phone = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int common_signin_button_text = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int common_signin_button_text_long = 2131034128;
			
			// aapt resource value: 0x7f05001b
			public const int default_status = 2131034139;
			
			// aapt resource value: 0x7f05001c
			public const int greeting_status = 2131034140;
			
			// aapt resource value: 0x7f05001e
			public const int greeting_status_error = 2131034142;
			
			// aapt resource value: 0x7f05001d
			public const int greeting_status_sign_in_required = 2131034141;
			
			// aapt resource value: 0x7f050013
			public const int list_moments_title = 2131034131;
			
			// aapt resource value: 0x7f05001f
			public const int loading_status = 2131034143;
			
			// aapt resource value: 0x7f050036
			public const int offline_access_disabled = 2131034166;
			
			// aapt resource value: 0x7f050032
			public const int plus_example_deep_link_id = 2131034162;
			
			// aapt resource value: 0x7f050033
			public const int plus_example_deep_link_url = 2131034163;
			
			// aapt resource value: 0x7f050034
			public const int plus_generic_error = 2131034164;
			
			// aapt resource value: 0x7f05002e
			public const int plus_one_medium_name = 2131034158;
			
			// aapt resource value: 0x7f05002d
			public const int plus_one_small_name = 2131034157;
			
			// aapt resource value: 0x7f050031
			public const int plus_one_standard_ann_name = 2131034161;
			
			// aapt resource value: 0x7f050030
			public const int plus_one_standard_name = 2131034160;
			
			// aapt resource value: 0x7f05002f
			public const int plus_one_tall_name = 2131034159;
			
			// aapt resource value: 0x7f05002c
			public const int plus_remove_moment_status = 2131034156;
			
			// aapt resource value: 0x7f050027
			public const int plus_write_moment_status = 2131034151;
			
			// aapt resource value: 0x7f05002a
			public const int plus_write_moment_status_auth_error = 2131034154;
			
			// aapt resource value: 0x7f050029
			public const int plus_write_moment_status_cached = 2131034153;
			
			// aapt resource value: 0x7f05002b
			public const int plus_write_moment_status_error = 2131034155;
			
			// aapt resource value: 0x7f050028
			public const int plus_write_moment_status_success = 2131034152;
			
			// aapt resource value: 0x7f050035
			public const int progress_message = 2131034165;
			
			// aapt resource value: 0x7f050017
			public const int revoke_access_button_name = 2131034135;
			
			// aapt resource value: 0x7f050026
			public const int revoke_access_error_status = 2131034150;
			
			// aapt resource value: 0x7f050025
			public const int revoke_access_status = 2131034149;
			
			// aapt resource value: 0x7f050014
			public const int send_interactive_button_name = 2131034132;
			
			// aapt resource value: 0x7f050018
			public const int server_auth_code_required_label = 2131034136;
			
			// aapt resource value: 0x7f050037
			public const int server_client_id = 2131034167;
			
			// aapt resource value: 0x7f05001a
			public const int share_prefill_text = 2131034138;
			
			// aapt resource value: 0x7f050019
			public const int share_title = 2131034137;
			
			// aapt resource value: 0x7f050024
			public const int sign_in_error_status = 2131034148;
			
			// aapt resource value: 0x7f050015
			public const int sign_in_profile_label = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int sign_out_button_name = 2131034134;
			
			// aapt resource value: 0x7f050021
			public const int signed_in_status = 2131034145;
			
			// aapt resource value: 0x7f050023
			public const int signed_out_status = 2131034147;
			
			// aapt resource value: 0x7f050020
			public const int signing_in_status = 2131034144;
			
			// aapt resource value: 0x7f050022
			public const int unknown_person = 2131034146;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingImageView = new int[]
			{
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] SignInButton = new int[]
			{
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
